# Master platform backlog (2026-10-06) as data. Generates
# docs/ops/MASTER_PLATFORM_BACKLOG_2026-10-06.md (python3 docs/ops/backlog/items.py).
# Fields: id, area, title, why, P, launch impact, effort, deps, safe in branch
# (Y/N/P=partly), owner action (Y/N), production access (Y/N), status, merged-from
# (other places the same item was recorded; counted as deduplicated candidates).
# Status: DONE (this branch, tested), QUEUED, BLOCKED-QC (needs Query C),
# BLOCKED-OWNER, BLOCKED-PROD (needs an approved production change),
# BLOCKED-EXT (external info), DEFERRED (P4 / after launch).
I = []
def a(id, area, title, why, p, impact, effort, deps, safe, owner, prod, status, merged=()):
    I.append(dict(id=id, area=area, title=title, why=why, p=p, impact=impact, effort=effort, deps=deps,
                  safe=safe, owner=owner, prod=prod, status=status, merged=list(merged)))

# ---------------- Inventory / stock (R1–R5)
a('INV-01','Inventory','Install R1 receive_purchase_order (all-or-nothing receive)','Double stock + duplicate expense on retry/drop (reproduced)','P0','Blocker','L','Query C; owner approval','N','Y','Y','BLOCKED-PROD',['PROJECT_RECORD R1','known bug 1','po-receive wanted test'])
a('INV-02','Inventory','Install R2 quarantine_recall','Quarantine twice / partial on drop','P0','Blocker','M','Query C; approval','N','Y','Y','BLOCKED-PROD',['R2','known bug 2'])
a('INV-03','Inventory','Install R3 receive_return','Double restock on drop','P0','Blocker','M','Query C; approval','N','Y','Y','BLOCKED-PROD',['R3','known bug 7'])
a('INV-04','Inventory','Install R4 adjust_inventory','Lost updates / below-zero race in the browser path','P0','Blocker','M','Query C; approval','N','Y','Y','BLOCKED-PROD',['R4','known bug 3'])
a('INV-05','Inventory','Install R5 delete_unused_product','Product delete atomicity','P1','High','S','approval','N','Y','Y','BLOCKED-PROD',['R5','known bug 5'])
a('INV-06','Inventory','Dashboard PR: call R1–R5 instead of multi-step table writes','The browser path stays non-atomic until switched','P0','Blocker','L','INV-01..05 installed','P','Y','N','BLOCKED-PROD')
a('INV-07','Inventory','R1–R5 drafts reconciled with Query A schema','Drafts were written on a guessed schema','P1','High','M','Query A','Y','N','N','DONE')
a('INV-08','Inventory','Product-first lock order in every draft workflow','Deadlocks delete vs receive/quarantine (control reproduces)','P1','High','S','—','Y','N','N','DONE')
a('INV-09','Inventory','Lot upsert on real unique index','Same new lot on two deliveries collided','P1','Medium','S','—','Y','N','N','DONE')
a('INV-10','Inventory','Optional expected-value (stale) check on adjust_inventory','Resent request / stale tab applied twice','P1','Medium','S','—','Y','N','N','DONE')
a('INV-11','Inventory','delete_unused_product: permission + any-bucket stock + 0-row check','False success under RLS; +5/−5 read as empty','P1','Medium','S','—','Y','N','N','DONE')
a('INV-12','Inventory','Failure injection at every write of R1–R4 (fingerprint unchanged)','Prove all-or-nothing','P1','High','M','—','Y','N','N','DONE')
a('INV-13','Inventory','Stress S10–S19 (60 stale tabs, hot row, delete races, killed connection…)','Concurrency proof','P1','High','M','—','Y','N','N','DONE')
a('INV-14','Inventory','Stress: 100 concurrent callers mixed across all R-functions, repeated','Push concurrency beyond 60–80 callers','P2','Medium','S','—','Y','N','N','DONE')
a('INV-15','Inventory','R-functions: recalled stock cannot be restocked/adjusted below zero by recall paths; quarantine twice on two recalls of one lot','Edge of over-quarantine (D-ops-4)','P2','Medium','S','D-ops-4','Y','Y','N','QUEUED')
a('INV-16','Inventory','One active recall per lot (partial unique index or status check)','Two recalls can quarantine the same lot twice','P1','Medium','S','D-ops-4; approval','P','Y','Y','BLOCKED-OWNER',['D-ops-4'])
a('INV-17','Inventory','Partial-quantity returns in the dashboard (p_quantity)','Today the whole line is restocked','P2','Medium','M','D-ops-5','P','Y','N','BLOCKED-OWNER',['D-ops-5'])
a('INV-18','Inventory','Expense date for received PO uses business date (Central)','UTC date wrong in US evenings: a delivery received after 7 pm on the 30th was logged in the next month (fixed in dashboard and R1, EXT4; D-ops-3 to confirm)','P1','High','S','D-ops-3 (confirm)','Y','N','N','DONE',['D-ops-3','PR #11 note','X4-09'])
a('INV-19','Inventory','Optional CHECK constraints (recalled >= 0, one expense per PO note)','Database-level safety net; Query B shows they apply cleanly','P2','Medium','S','approval','N','Y','Y','BLOCKED-PROD')
a('INV-20','Inventory','Revoke direct table writes on stock tables after R1–R5 (functions become the only path)','Legacy direct-write path bypasses the checks','P1','High','S','INV-06; Query C §8; approval','N','Y','Y','BLOCKED-PROD')
a('INV-21','Inventory','Rollout order R1 → R4 → R2 → R3 → R5','Money impact first','P1','High','S','D-ops-1','N','Y','N','BLOCKED-OWNER',['D-ops-1'])
a('INV-22','Inventory','Agents/automations writing stock directly (D-ops-6)','Would bypass R1–R5','P0','Blocker','S','Query C §5–7','N','Y','N','BLOCKED-QC',['D-ops-6'])
a('INV-23','Inventory','Browser: claim-first receive/return/recall; compare-and-set stock','Interim protection until R1–R5','P1','High','M','—','Y','N','N','DONE',['overnight 10-05'])
a('INV-24','Inventory','Product delete: permission, in-use check, stock row restore','False success; lost stock row','P1','High','S','—','Y','N','N','DONE')
a('INV-25','Inventory','Whole-unit catalogue PO lines; deleted POs locked; case-insensitive SKU','Real schema alignment','P1','High','S','Query A','Y','N','N','DONE')
a('INV-26','Inventory','Employee restock refused up front','Half-received return','P1','High','S','Query A','Y','N','N','DONE')
a('INV-27','Inventory','SQL draft tests for lot numbers with only whitespace / unicode / mixed case duplicates','Lot identity edge cases','P3','Low','S','—','Y','N','N','DONE')
a('INV-28','Inventory','Wanted (test.fail) atomicity tests flip to passing once dashboard calls R1–R4','Keeps the goal visible','P3','Low','S','INV-06','Y','N','N','BLOCKED-PROD')

# ---------------- State machine / contracts
a('SM-01','State machine','Mock enforces Query A CHECK rules on every write; impossible-data guard','Class of "denied" bugs','P1','High','M','Query A','Y','N','N','DONE')
a('SM-02','State machine','Document categories match DB (5 of 10 refused)','Uploads failed','P1','High','S','—','Y','N','N','DONE')
a('SM-03','State machine','Static audit of dropdowns, maps, transitions, literals','Coverage of unclicked values','P1','High','S','—','Y','N','N','DONE')
a('SM-04','State machine','Add Query C §9 rules (incidents, legal holds, FR, QC, inquiries, service_status, system_mode, enums) to db-constraints.js','Remaining tables unverified','P1','High','S','Query C','Y','N','N','BLOCKED-QC')
a('SM-05','State machine','incidents.severity accepts "normal"? (recall/QC escalation)','Escalation could fail for normal severity','P1','Medium','S','Query C §9','Y','N','N','BLOCKED-QC')
a('SM-06','State machine','orders.channel enum vs manual order entry values','A manual sale type could be refused','P1','Medium','S','Query C §9','Y','N','N','BLOCKED-QC')
a('SM-07','State machine','Approval Deny writes "rejected"; rejected = closed everywhere','Live bug (Query A)','P0','High','S','—','Y','N','N','DONE')
a('SM-08','State machine','Tasks: no transition out of done/cancelled; buttons have DB guards','Backwards moves','P1','Medium','S','—','Y','N','N','DONE')
a('SM-09','State machine','Feature requests: status advance guard + values vs DB','Unverified values','P2','Low','S','Query C §9','Y','N','N','BLOCKED-QC')
a('SM-10','State machine','Returns: re-open after refund impossible; approve only from requested','N13 finding','P1','High','S','—','Y','N','N','DONE',['N13'])
a('SM-11','State machine','Purchase orders: no backwards move; Cancel only draft/ordered/shipped','Cancel-after-receive','P1','High','S','—','Y','N','N','DONE')
a('SM-12','State machine','Document link types: supplier or none','Live bug (Query A)','P0','High','S','—','Y','N','N','DONE')
a('SM-13','State machine','Recall resolve needs note; never-quarantined needs second press','Compliance record','P1','Medium','S','—','Y','N','N','DONE')
a('SM-14','State machine','Legal hold release only active; FDA flag only once','Compliance','P1','Medium','S','—','Y','N','N','DONE')
a('SM-15','State machine','Customer inquiry "answered" guarded; severity/draft unguarded','Last write wins on drafts','P3','Low','S','—','Y','N','N','DONE')
a('SM-16','State machine','Service status change unguarded (stale overwrite)','Low consequence','P3','Low','S','—','Y','N','N','DONE')
a('SM-17','State machine','Agent switch / flag / system mode guarded','Stale tab flips','P1','High','S','—','Y','N','N','DONE')

# ---------------- Mutations / permissions / UX honesty
a('MU-01','Mutations','Silent RLS refusals reported as success (10 paths)','False "done"','P1','High','M','—','Y','N','N','DONE')
a('MU-02','Mutations','Escalate to incident at most once (QC, recall)','Duplicate/orphan incidents','P1','Medium','S','—','Y','N','N','DONE')
a('MU-03','Mutations','PO payment status guarded','Stale Paid → Unpaid','P2','Medium','S','—','Y','N','N','DONE')
a('MU-04','Mutations','Second press on Receive delivery and Mark Refunded','One-click irreversible','P2','Medium','S','—','Y','N','N','DONE')
a('MU-05','Mutations','Reminder double submit (form + quick add Enter)','Duplicates','P3','Low','S','—','Y','N','N','DONE')
a('MU-06','Mutations','Emergency mode: Shopify sync off / Agent #7 pause failures only logged to console; page says success','In an emergency the owner believes sync is off when it is not','P1','High','S','—','Y','N','N','DONE')
a('MU-07','Mutations','Sweep: every remaining .update/.delete without row check (calendar, inquiries, service status, reminders dismiss)','Complete the silent-refusal class','P2','Medium','S','—','Y','N','N','DONE')
a('MU-08','Mutations','Raw DB/RLS errors: plain explanation without hiding detail','Owner understands refusals','P2','Medium','S','—','Y','N','N','DONE')
a('MU-09','Mutations','Raw errors still show table/policy names (e.g. "for table evidence_locker")','Unnecessary internal detail in UI','P3','Low','S','—','Y','N','N','DONE')
a('MU-10','Mutations','Owner / Administrator / employee behaviour tested separately for each owner-only action','Role regressions','P2','Medium','M','—','Y','N','N','DONE')
a('MU-11','Mutations','Legal hold should block deletes of related records?','Compliance meaning of a hold','P1','Medium','M','owner decision','P','Y','N','BLOCKED-OWNER')
a('MU-12','Mutations','Product edit concurrent-edit guard (updated_at)','Last save wins','P3','Low','S','—','Y','N','N','DEFERRED')
a('MU-13','Mutations','Session revoke (rpc) result not checked for "nothing revoked"','Could claim a device was logged out','P2','Medium','S','—','Y','N','N','DONE')
a('MU-14','Mutations','Business rules threshold: stale overwrite (config) unguarded','Two owners editing','P3','Low','S','—','Y','N','N','DONE')
a('MU-15','Mutations','Password re-check Enter-twice sends two checks','PR #13','P2','Low','S','—','Y','N','N','DONE',['PR #13'])

# ---------------- Storage / uploads
a('ST-01','Storage','Saved record never loses its file on dropped reply','Data loss','P0','High','S','—','Y','N','N','DONE')
a('ST-02','Storage','Evidence/receipt orphan cleanup; document delete removes file','Orphans','P1','Medium','S','—','Y','N','N','DONE',['security review S10'])
a('ST-03','Storage','Size/type check before upload','Late failure; active content','P2','Low','S','—','Y','N','N','DONE')
a('ST-04','Storage','Receipt delete: storage removed but DB clear fails → record points at missing file','Documented, acceptable; test it','P3','Low','S','—','Y','N','N','DONE')
a('ST-05','Storage','Malicious filenames (path traversal, unicode, very long) produce safe storage paths','Path safety','P2','Medium','S','—','Y','N','N','DONE')
a('ST-06','Storage','Path collision: same name in the same millisecond','Upload error','P3','Low','S','—','Y','N','N','DONE')
a('ST-07','Storage','Read-only check of bucket privacy, size limits, MIME rules and storage policies','Unknown production settings','P1','Medium','S','owner runs a read-only check','N','Y','Y','BLOCKED-PROD')
a('ST-08','Storage','Read-only listing of orphaned objects created before the fixes','Cleanup scope','P3','Low','S','owner','N','Y','Y','BLOCKED-PROD')
a('ST-09','Storage','Server-side atomic upload+record (signed upload + DB function) design','Browser cannot make two systems atomic','P3','Low','M','design only','Y','N','N','DONE')
a('ST-10','Storage','Signed-URL lifetime (60 s) and download link behaviour documented','Expired links','P4','Low','S','—','Y','N','N','DEFERRED')

# ---------------- Reporting / money
a('RP-01','Reporting','Totals complete beyond 1,000 rows (Accounting, Tax, Business Health, Daily Summary)','Silent undercount','P0','High','M','—','Y','N','N','DONE',['N14'])
a('RP-02','Reporting','Boundary tests 0/1/999/1,000/1,001/10,000 rows for Accounting and Tax totals','Off-by-one at page edges','P2','Medium','S','—','Y','N','N','DONE')
a('RP-03','Reporting','Refund accounting decision N4 (subtract vs full)','Revenue correctness','P1','High','S','owner decision','P','Y','N','BLOCKED-OWNER',['N4'])
a('RP-04','Reporting','Accounting/Tax date ranges in Central time vs UTC','Evening orders counted on the wrong day','P1','Medium','S','D-ops-3 / owner','P','Y','N','BLOCKED-OWNER',['PR #11 note'])
a('RP-05','Reporting','Deleted (soft) orders and expenses excluded from all totals — test','Double counting','P2','Medium','S','—','Y','N','N','DONE')
a('RP-06','Reporting','Duplicate PO expenses detection in reports','Duplicate expense visibility','P3','Low','S','—','Y','N','N','DONE')
a('RP-07','Reporting','Tax CSV export = figures on screen at scale (2,500 rows)','Export truncation','P2','Medium','S','—','Y','N','N','DONE')
a('RP-08','Reporting','Partial refunds counted in full (listed for review)','Known limitation','P2','Medium','M','N4','P','Y','N','BLOCKED-OWNER')
a('RP-09','Reporting','Sales tax by state requires state field on real orders','Unverified until first real order','P2','Medium','S','first real order','N','Y','N','BLOCKED-EXT')
a('RP-10','Reporting','report_totals draft reconciled with real NOT NULL columns (orders.channel, returns.reason)','Draft test assumed the guessed schema','P2','Medium','S','Query A','Y','N','N','DONE')
a('RP-10','Reporting','AI spend this month complete beyond 1,000 log rows','Spend cap check','P2','Medium','S','—','Y','N','N','DONE')

# ---------------- Scale / pagination
a('SC-01','Scale','Calendar notes batched; inquiry orders chunked','URL overflow','P2','Medium','S','—','Y','N','N','DONE')
a('SC-02','Scale','Activity "Export to spreadsheet" exports only the rows loaded, silently','Partial audit export','P2','Medium','S','—','Y','N','N','DONE')
a('SC-03','Scale','Activity "Today" digest capped at 500 shows "500 changes"','Undercount','P2','Low','S','—','Y','N','N','DONE')
a('SC-04','Scale','Record Inspector history: 200 search matches filtered client-side → incomplete history','Audit view incomplete','P2','Medium','S','—','Y','N','N','DONE')
a('SC-05','Scale','"Showing first 1,000" notice for long lists (lots, products, POs)','Silent list truncation later','P3','Low','S','—','Y','N','N','DEFERRED')
a('SC-06','Scale','Lot pickers truncate after 1,000 lots','Older lots missing from pickers','P3','Low','S','—','Y','N','N','DEFERRED')
a('SC-07','Scale','Single reusable paging helper used by all totals (fetchAllRows/In)','Consistency','P3','Low','S','—','Y','N','N','DONE')
a('SC-08','Scale','Search (sidebar/palette) loads only already-loaded records — document','Search scope','P4','Low','S','—','Y','N','N','DEFERRED')

# ---------------- Security
a('SE-01','Security','Query D: elevated functions callable by anon — classify and review','Possible unauthenticated writes','P0','High','S','owner runs Query D','N','Y','Y','BLOCKED-OWNER')
a('SE-02','Security','Permission fixes from Query D (revoke/grant, gates)','Depends on Query D','P0','High','M','SE-01; approval','N','Y','Y','BLOCKED-PROD')
a('SE-03','Security','Escape output on search.html / dashboard.html','XSS','P1','High','S','—','Y','N','N','DONE',['R6','PR #7'])
a('SE-04','Security','Pin + SRI Supabase library on all pages','Supply chain','P1','High','S','—','Y','N','N','DONE',['R7'])
a('SE-05','Security','XSS second payload family across every text field','Escaping coverage','P1','High','S','—','Y','N','N','DONE')
a('SE-06','Security','CSV formula guard (= + - @ tab CR)','Spreadsheet injection','P1','Medium','S','—','Y','N','N','DONE',['PR #9'])
a('SE-07','Security','Link scheme allowlist (javascript:, data:, vbscript:)','Clickable code','P1','Medium','S','—','Y','N','N','DONE',['PR #10'])
a('SE-08','Security','Activity export CSV formula injection test (person/record text)','Second export path','P2','Medium','S','—','Y','N','N','DONE')
a('SE-09','Security','Bidi/RTL override and zero-width characters in names shown with clear isolation','Spoofed display text','P3','Low','S','—','Y','N','N','DONE')
a('SE-10','Security','Public repo hygiene scan in CI (no keys/emails in added files)','Prevent leaks','P3','Low','S','—','Y','N','N','DONE')
a('SE-11','Security','Password re-check covers every destructive action (matrix complete)','Consistency','P2','Medium','S','—','Y','N','N','DONE')
a('SE-12','Security','Task access hardening before more staff','Least privilege','P2','Medium','M','owner','N','Y','Y','BLOCKED-OWNER',['owner list'])
a('SE-13','Security','Failed-login history / login alerts','Detect account abuse','P4','Low','M','server side','N','Y','Y','DEFERRED',['owner list'])

# ---------------- Agents / automation
a('AG-01','Agents','Agent #1 (invoices) state verified ON before real orders','Orders without invoices','P0','Blocker','S','Query C §1/§3','N','Y','N','BLOCKED-QC',['pending check 5'])
a('AG-02','Agents','Truthful agent state (Unknown/Failed/Stale/Dry run)','No optimistic defaults','P1','High','M','—','Y','N','N','DONE')
a('AG-03','Agents','"error"/"fail" statuses show Failed; Agent #1 "Switch on"','Overclaim','P2','Medium','S','—','Y','N','N','DONE')
a('AG-04','Agents','Scheduled jobs list vs dashboard cron names reconciled','Stale job names','P2','Medium','S','Query C §5','Y','N','N','BLOCKED-QC')
a('AG-05','Agents','Shopify sync interlock + wording; Emergency switches it off','Premature sync','P1','High','S','—','Y','N','N','DONE',['R9'])
a('AG-06','Agents','No-send tripwires (email, Shopify)','No customer messages','P1','High','S','—','Y','N','N','DONE',['R10'])
a('AG-07','Agents','Agent run-history view','Operational visibility','P4','Low','M','—','Y','N','N','DEFERRED',['owner list'])
a('AG-08','Agents','Agent #8 migration to Supabase with dedupe','Reliability','P4','Low','L','owner','N','Y','Y','DEFERRED',['owner list'])
a('AG-09','Agents','Re-enable workflows / Shopify sync at launch','Operations','P1','Blocker','S','products; R1–R4','N','Y','Y','BLOCKED-OWNER',['R9'])
a('AG-10','Agents','Agent #6 real email service decision','Customer messages','P2','Medium','M','owner','N','Y','Y','BLOCKED-OWNER',['R10'])

# ---------------- Store / Shopify
a('SH-01','Shopify','Real products with exact SKUs (dashboard = Shopify)','Returns/receives find products by SKU','P1','Blocker','S','owner','N','Y','Y','BLOCKED-OWNER',['R8'])
a('SH-02','Shopify','Sync design decision (D-4)','How orders/stock flow','P1','Blocker','M','owner','N','Y','N','BLOCKED-OWNER',['D-4'])
a('SH-03','Shopify','Order status words match Accounting/Tax classification after launch','Revenue classification','P2','Medium','S','first real orders','N','Y','N','BLOCKED-EXT',['pending check 4'])

# ---------------- Empty / partial states
a('EM-01','Empty states','Every page clean on empty DB; products without movement','First launch','P2','Medium','S','—','Y','N','N','DONE')
a('EM-02','Empty states','System mode default shown as default, not as saved','Unknown ≠ Normal','P2','Medium','S','—','Y','N','N','DONE')
a('EM-03','Empty states','Business Health "Paused agents 0" when agent switches could not be read','Unknown shown as zero','P2','Medium','S','—','Y','N','N','DONE')
a('EM-04','Empty states','Pages when a single loader fails (one table errors) — rest still render, error says which','Partial failure','P2','Medium','S','—','Y','N','N','DONE')
a('EM-05','Empty states','Missing feature_flags row for shopify_order_sync: say "not configured", not "off"','Unknown vs off','P2','Medium','S','—','Y','N','N','DONE')
a('EM-06','Empty states','Product without inventory row: Inventory page shows it with "no stock row" warning','Broken invariant visible','P3','Low','S','—','Y','N','N','DONE')

# ---------------- Accessibility / responsive
a('AX-01','Accessibility','Accessible names, unique ids, phone tap targets, dialog focus','Screen readers / phone','P2','Medium','S','—','Y','N','N','DONE')
a('AX-02','Accessibility','Status/error banner announced to screen readers (role=alert / aria-live)','Errors not announced','P2','Medium','S','—','Y','N','N','DONE')
a('AX-03','Accessibility','Toasts announced (aria-live polite)','Success not announced','P3','Low','S','—','Y','N','N','DONE')
a('AX-04','Accessibility','prefers-reduced-motion respected for animations','Motion sensitivity','P3','Low','S','—','Y','N','N','DONE')
a('AX-05','Accessibility','Keyboard: every overlay closes with Escape and returns focus','Keyboard users','P2','Medium','S','—','Y','N','N','DONE')
a('AX-06','Accessibility','Colour contrast check of badges in light/dark','Readability','P3','Low','S','—','Y','N','N','DONE')
a('AX-07','Accessibility','Dark theme: white text on bright blue/red fills (buttons 3.0:1, Delete 2.8:1) and default-blue links (1.8:1)','Found by the AA contrast test (2026-10-06)','P2','Medium','S','—','Y','N','N','DONE')
a('AX-08','Accessibility','64 hard-coded grey inline text colours ignored the theme (labels 1.6:1 in dark; dates 3.1:1 in light)','Found by the AA contrast test (2026-10-06)','P2','Medium','S','—','Y','N','N','DONE')
a('AX-09','Accessibility','Contrast of text inside plain divs/spans (test covers badges, buttons, hints, empty states, labels, links, stat labels)','Remaining coverage gap','P3','Low','S','—','Y','N','N','DONE')
a('RS-01','Responsive','Key workflows at narrow desktop (800px) and tablet (768px)','Untested widths','P2','Medium','S','—','Y','N','N','DONE')
a('RS-02','Responsive','Phone swipe in tables; PO tap opens history','PR #12, #14','P2','Medium','S','—','Y','N','N','DONE',['PR #12','PR #14'])
a('RS-03','Responsive','Real iPhone Safari check of task buttons','Chromium only in tests','P2','Medium','S','owner','N','Y','N','BLOCKED-OWNER',['pending check 1'])

# ---------------- Search / palette / calendar / misc UX
a('UX-01','UX','Sidebar search: typing a page name + Enter opens that page (test.fixme)','Fixed EXT3: page name wins on Enter (sidebar + palette); questions still open the Guide','P3','Low','S','owner decision','Y','Y','N','DONE',['general.spec fixme','known bug 11'])
a('UX-02','UX','Palette first keys lost after Cmd+K','Typing lost','P3','Low','S','—','Y','N','N','DONE')
a('UX-03','UX','US-evening dates (expense/AE defaults, lot expiry, file names, tax receipt list)','Off by one day','P2','Medium','S','—','Y','N','N','DONE',['PR #11','known bug 9'])
a('UX-04','UX','Stale agent status text #2/#3/#7/#8','Wording','P3','Low','S','—','Y','N','N','DONE',['PR #8'])
a('UX-05','UX','"Recently done + Reopen" on Tasks','Owner wish','P4','Low','M','—','Y','N','N','DEFERRED',['owner list'])
a('UX-06','UX','Administrator tries personal calendar','Pending check','P3','Low','S','owner','N','Y','N','BLOCKED-OWNER',['pending check 2'])

# ---------------- Tests / CI / harness
a('TQ-01','Tests','Flaky palette tests fixed at root; employee delete test robust','Trust in suite','P3','Medium','S','—','Y','N','N','DONE')
a('TQ-02','Tests','Mutation tests for page-side guards (stale guard, noRowsChanged, escaping, paging, upload cleanup)','Prove tests bite','P3','Medium','M','—','Y','N','N','DONE')
a('TQ-03','Tests','Mock: DELETE representation, ilike, constraints, URL limits','Realism','P3','Medium','S','—','Y','N','N','DONE')
a('TQ-04','Tests','Mock refuses NOT NULL omissions for all Query A columns (not only status columns)','Inserts missing required fields','P3','Medium','S','—','Y','N','N','DONE')
a('TQ-05','Tests','Request baseline kept current','Unexpected requests','P3','Low','S','—','Y','N','N','DONE')
a('CI-01','CI','Tests-only workflow ready, least privilege','Automated checks','P2','Medium','S','—','Y','N','N','DONE')
a('CI-02','CI','Activate CI (owner opens/merges the PR) and make Playwright required','Gate merges','P2','Medium','S','owner','N','Y','Y','BLOCKED-OWNER')
a('CI-03','CI','Verify pinned action SHAs against release tags','Supply chain','P2','Low','S','owner (other repos out of scope)','N','Y','N','BLOCKED-OWNER')
a('CI-04','CI','Optional SQL job (local Postgres service) for draft tests','Draft regressions caught in CI','P3','Low','M','CI-02','Y','Y','N','DONE')
a('CI-05','CI','Secret/PII scan step in CI','Public repo hygiene','P3','Low','S','—','Y','N','N','DONE')

# ---------------- Modularization / maintainability
a('MD-01','Modularization','Steps 1, 2, 2b (CSS, icon, 28 pure helpers)','Smaller main file','P3','Low','M','—','Y','N','N','DONE')
a('MD-02','Modularization','Move confirmSecondPress + small DOM helpers','Next safe slice','P3','Low','S','—','Y','N','N','DONE')
a('MD-03','Modularization','HE namespace + start registry + feature modules','Plan step 3','P3','Low','L','open PRs merged','N','Y','N','BLOCKED-OWNER')
a('MD-04','Modularization','Upload helpers (uploadThenSave) to a module with supabase injected','Reuse/testing','P3','Low','S','—','Y','N','N','QUEUED')

# ---------------- Extension 3 second-pass audit (2026-10-06; docs/ops/SECOND_PASS_AUDIT_2026-10-06.md)
a('X3-01','State machine','Product edit form wrote status unguarded (stale tab flips discontinued/active)','Found by the mock state rule','P2','Medium','S','—','Y','N','N','DONE')
a('X3-02','State machine','Order Restore without "still deleted" condition','Found by the mock state rule','P3','Low','S','—','Y','N','N','DONE')
a('X3-03','Reporting','Expenses page count and money total summed from the newest 200 only','Silent wrong money total beyond 200 expenses','P1','High','S','—','Y','N','N','DONE')
a('X3-04','Scale','Returns page listed and counted the newest 200 only (old open returns vanished)','Open work hidden','P2','Medium','S','—','Y','N','N','DONE')
a('X3-05','Validation','Blank Business Rules value saved as 0','Number("") is 0','P3','Low','S','—','Y','N','N','DONE')
a('X3-06','Validation','Negative / infinite numbers accepted on button-saved fields (PO shipping/tax, prices, threshold)','No browser form check on plain buttons','P3','Low','S','—','Y','N','N','DONE')
a('X3-07','Dates','Cleared expense date fell back to the UTC date','"Tomorrow" on US evenings','P3','Low','S','—','Y','N','N','DONE')
a('X3-08','Query C','Query C failed without pg_cron; tokens not masked in agent errors','Owner run could stop with an error','P2','Medium','S','—','Y','N','N','DONE')
a('X3-09','Inventory','R1–R5 install had no schema preflight (wrong shape installs, fails at first click)','Install safety','P1','High','S','—','Y','N','N','DONE')
a('X3-10','Tests','Hostile-filename test raced the form reset under load','Flake','P3','Low','S','—','Y','N','N','DONE')
a('X3-11','Scale','Return-form order picker lists newest 200 orders only','Old order returns can\'t be logged','P3','Low','S','volume','Y','N','N','DEFERRED')
a('X3-12','Scale','Evidence form incident picker newest 200 only','Years away','P3','Low','S','volume','Y','N','N','DEFERRED')
a('X3-13','Inventory','Sold product (order lines by SKU text) could be deleted (dashboard + R5)','Sales history points at nothing; returns can\'t restock','P2','Medium','S','—','Y','N','N','DONE')
a('X3-14','Inventory','Product with a quality check could be deleted (dashboard); database FK unknown','Orphan QC rows','P3','Low','S','Query C §9','Y','N','N','DONE')
a('X3-15','Inventory','Tasks can name a deleted product by id (free text)','Low impact','P3','Low','S','—','Y','N','N','DEFERRED')
a('X3-16','Inventory','Keep permanent product delete limited to never-used products, or archive only?','Policy','P3','Low','S','owner','N','Y','N','BLOCKED-OWNER')
a('X3-17','Agents','Emergency Order Sync switch-off writes updated_by/updated_at to feature_flags (columns unverified)','Switch-off could always fail; branch fallback added','P1','High','S','Query C §10','P','N','N','BLOCKED-QC')
a('X3-18','Audit','Compliance actions record when but not who (legal hold, FDA, QC, inquiries)','Who-did-it lost if no audit trigger','P2','Medium','M','Query C §10; approval','N','Y','Y','BLOCKED-QC')
a('X3-19','Audit','Send actor fields on more writes once columns are confirmed','Blind columns break writes','P3','Low','S','Query C §10','Y','N','N','BLOCKED-QC')
a('X3-20','Orders','Manual order retry after a failure created a SECOND order (duplicate revenue)','Two-step save, lost reply','P1','High','S','—','Y','N','N','DONE')
a('X3-21','Auth','Signed out in another tab: dashboard stayed open showing empty lists as if no data','Unknown shown as empty','P2','Medium','S','—','Y','N','N','DONE')
a('X3-22','Errors','Raw "Failed to fetch" / database text on dropped connections and other pages','Misleading "not saved"; internal names','P2','Medium','S','—','Y','N','N','DONE')
a('X3-23','Auth','Threshold save had no role check (employee request sent, refused by database)','Inconsistent with other stock actions','P3','Low','S','—','Y','N','N','DONE')
a('X3-24','Tests','SQL mutation run found 3 untested rules (recalled floor, fully received lines, unapproved return)','Test gaps','P2','Medium','S','—','Y','N','N','DONE')
a('X3-25','Docs','Backup health unverified; records disagree (kept on vs last ran Sept 13)','Restore readiness unknown','P1','High','S','owner check','N','Y','N','BLOCKED-OWNER')

a('X3-26','Storage','Zero-byte files uploaded and saved as empty receipts/documents','Useless record looks saved','P3','Low','S','—','Y','N','N','DONE')
a('X3-27','Storage','Document delete from a stale tab removed record + old file, orphaning a replaced file','Orphan file','P3','Low','S','—','Y','N','N','DONE')

a('X3-28','Accessibility','Keyboard focus not returned to the opener when a dialog closed (6 dialogs)','WCAG 2.4.3; keyboard users lost their place','P2','Medium','S','—','Y','N','N','DONE')
a('X3-29','Accessibility','No dialog was announced as a dialog (role, aria-modal, label)','Screen readers did not say a dialog opened','P2','Medium','S','—','Y','N','N','DONE')
a('X3-30','Tests','"Every overlay closes with Escape" silently skipped the Record Inspector (opened by click, which never opens it)','False confidence','P3','Low','S','—','Y','N','N','DONE')
a('X3-31','Search','Guide matching is single-word fuzzy: gibberish with a common word lists unrelated articles','Relevance','P4','Low','S','—','Y','N','N','DEFERRED')

a('X3-32','Orders','Manual order date stored as midnight UTC = 7 pm the PREVIOUS day in Central (wrong day; on the 1st the wrong month) and default date was "tomorrow" after 7 pm','Live on main: misplaced revenue in Accounting/Tax','P1','High','S','—','Y','N','N','DONE')

# ---------------- Extension 3 final review: future items (each with evidence)
a('F3-01','Accessibility','Input and control borders in light mode ~1.4:1 (37 inline #cfd8d6 + theme --field-border) vs WCAG 1.4.11 3:1','Hard to see field edges','P3','Low','S','design decision','Y','Y','N','BLOCKED-OWNER')
a('F3-02','Orders','Manual orders record no SKU (product name only): returns of manual orders cannot restock by SKU; sold-product check cannot see manual sales','manual-order-entry itemsPayload has no sku','P2','Medium','M','owner: product picker','P','Y','N','BLOCKED-OWNER')
a('F3-03','Orders','Manual order number has 1-second resolution (M-YYYYMMDD-HHMMSS): two devices in the same second collide','generateOrderNumber','P3','Low','S','Query C §9 (is order_number unique?)','Y','N','N','BLOCKED-QC')
a('F3-04','Auth','dashboard.html / search.html / manual-order-entry.html do not react to sign-out in another tab','no onAuthStateChange (order entry re-checks the user before saving)','P3','Low','S','—','Y','N','N','DONE')
a('F3-05','Search','Palette record results cap at 30 without saying "more…"','searchEverything slice(0,30)','P4','Low','S','—','Y','N','N','DEFERRED')
a('F3-06','Agents','Agent error text shown on the agents page is not masked like in Query C (emails/tokens)','last_error rendered as text','P3','Low','S','—','Y','N','N','DONE')
a('F3-07','Reports','Accounting "This Week" is the last 7×24 h, not Monday–Sunday; label could mislead','acctRangeStart week = now − 7 days','P3','Low','S','owner wording','Y','Y','N','BLOCKED-OWNER')
a('F3-08','Storage','Receipt/document file type is checked by extension only (not content)','uploadProblem uses the name','P3','Low','S','—','Y','N','N','DEFERRED')
a('F3-09','Inventory','Low-stock threshold has no stale-tab guard (last write wins on a config value)','upsert without condition (fixed in EXT5 as X5-16; status reconciled EXT6)','P4','Low','S','—','Y','N','N','DONE',['X5-16'])
a('F3-10','Tests','Visual baselines exist for 2 sizes only; device matrix checks layout, not pixels','visual.spec','P4','Low','M','—','Y','N','N','DEFERRED')
a('F3-11','CI','Mutation harnesses are not in CI (20 min page run)','run-page-mutations.js','P4','Low','S','CI-02','Y','Y','N','DEFERRED')
a('F3-12','Docs','Owner-facing "what each page does" guide is spread across Guide articles; no printable one-pager','help entries in page','P4','Low','M','—','Y','N','N','DEFERRED')
a('F3-13','Performance','owner-login.html still ~500 KB in one file; first load parses everything','file size','P3','Low','L','modularization step 3','Y','Y','N','BLOCKED-OWNER')
a('F3-14','Security','No Content-Security-Policy meta on the pages (GitHub Pages cannot set headers)','pages have no CSP','P3','Medium','M','test inline handlers first','Y','N','N','DONE')
a('F3-15','Data','Existing manual orders entered before X3-32 may sit one day early','date bug on main','P3','Low','S','owner (pre-launch: likely none)','N','Y','Y','BLOCKED-OWNER')

# ---------------- Docs / process / owner
a('DOC-01','Docs','Audits recorded (state machine, mutations, storage, pagination, launch readiness)','Durable record','P3','Medium','S','—','Y','N','N','DONE')
a('DOC-02','Docs','Merge order for open PRs #5–#24 and this branch','Safe rollout','P2','High','S','owner','Y','Y','N','BLOCKED-OWNER',['pr-merge-order.md'])
a('DOC-03','Docs','Owner runbook: how to install R1–R5 and roll back (click-by-click)','Production change by owner','P1','High','S','—','Y','N','N','DONE')
a('DOC-04','Docs','Mark superseded statements in older docs (guessed schema, "BLOCKED ON QUERY A/B")','Stale docs','P3','Low','S','—','Y','N','N','DONE')
a('DOC-05','Docs','Task v2 live checks (refresh, audit_log, Cancel, iPhone, 2nd account)','Pending owner checks','P2','Medium','S','owner','N','Y','N','BLOCKED-OWNER',['pending check 1'])
a('DOC-06','Docs','Document category list decision','DB rule vs wishes','P2','Low','S','owner','N','Y','Y','BLOCKED-OWNER')
a('DOC-07','Docs','Query C run and results analysed','Unblocks SM-04..06, INV-22, AG-01/04','P0','Blocker','S','owner runs it','N','Y','Y','BLOCKED-OWNER')
a('DOC-08','Docs','Activity-log retention policy','Storage growth / privacy','P4','Low','S','owner','N','Y','N','DEFERRED',['owner list'])
a('DOC-09','Docs','Invoice status decision (issued vs draft)','Agent #1 output','P3','Low','S','owner','N','Y','N','BLOCKED-OWNER',['owner list'])

# ---------------- Extension 4 (2026-10-06, deep readiness)
a('X4-01','State machine','Feature request "Mark in progress" from a stale tab could jump to done','It re-read the database status instead of the shown one','P2','Medium','S','—','Y','N','N','DONE')
a('X4-02','State machine','Expense and feature-request Restore only while still deleted','Stale restore wrote over newer state','P3','Low','S','—','Y','N','N','DONE')
a('X4-03','Double submit','Procedure form had no double-submit lock (found by the write-path inventory)','Duplicate procedures','P3','Low','S','—','Y','N','N','DONE')
a('X4-04','Orders','Manual order retry matched on the total only','Changed lines were silently dropped or attached to the first attempt','P1','High','S','—','Y','N','N','DONE')
a('X4-05','Orders','Two tabs saving in the same second adopted each other\'s order','A whole order could be lost (merged into another)','P1','High','S','—','Y','N','N','DONE',['F3-03 (partly)'])
a('X4-06','Orders','Unfinished manual-order attempt survives a reload, with a warning','Re-entering after a reload created a duplicate','P2','Medium','S','—','Y','N','N','DONE')
a('X4-07','Errors','Gateway error pages / cut-off replies / rate limits shown as raw text','Raw HTML on screen; outcome unknown not said','P2','Medium','S','—','Y','N','N','DONE')
a('X4-08','Inventory','Product delete: lost reply on the final step put a stock row back for a deleted product','Stray stock row / "not deleted" when it was','P2','Medium','S','—','Y','N','N','DONE')
a('X4-10','Accounting','Accounting "Last 7 days" left out expenses dated 7 days ago after 7 pm; UTC slices for viewers east of UTC','Totals off by a day','P2','Medium','S','—','Y','N','N','DONE')
a('X4-11','Scale','Whole-table lists silently stop at 1,000 rows: notice added','A list could look complete when it is not','P2','Medium','S','—','Y','N','N','DONE',['pagination audit "watch later"'])
a('X4-12','Money','PO grand total saved with floating-point junk / fractions of a cent (dashboard and R1)','Expense 0.30000000000000004','P2','Medium','S','—','Y','N','N','DONE')
a('X4-13','Money','Refund amount accepted fractions of a cent and huge values','Accounting data quality','P2','Medium','S','—','Y','N','N','DONE')
a('X4-14','Validation','Add-product prices had no upper limit; numeric contract for every number box','Typos saved','P3','Low','S','—','Y','N','N','DONE')
a('X4-15','Inventory','Removing / adding / re-quantifying a PO line while the order is received makes order and stock disagree (delete 4–7, add 5, qty 6 of 20 races, even with R1); guard extended in EXT5','Stock vs records mismatch','P1','High','S','R1; approval','P','Y','Y','BLOCKED-PROD',['CONCURRENCY_MATRIX'])
a('X4-16','Inventory','R1–R5 install preflight checks column types; install tests for missing table, hostile search_path, owner, reinstall','Wrong shape installs and fails later','P2','Medium','S','—','Y','N','N','DONE')
a('X4-17','Emergency','Emergency mode skipped switching off Order Sync / pausing Agent #7 when recording the mode failed','In an emergency the sync could stay on','P1','High','S','—','Y','N','N','DONE')
a('X4-18','Accessibility','Skip link and keyboard focus kept inside dialogs','WCAG 2.4.1 / 2.4.3','P2','Medium','S','—','Y','N','N','DONE')
a('X4-19','Search','Command palette order: pages, records, then Guide','Requested order','P3','Low','S','—','Y','N','N','DONE')
a('X4-20','Errors','Developer wording on screen ("send me the exact message"); static check added','Confusing for staff','P3','Low','S','—','Y','N','N','DONE')
a('X4-21','Tests','Mock value rules must match the schema evidence (drift gate)','Tests passing against rules the database lacks','P3','Medium','S','—','Y','N','N','DONE')
a('X4-22','Tests','Write-path inventory (98 paths) with stale / read-back / lock gate','New write paths can\'t skip a guard silently','P3','Medium','M','—','Y','N','N','DONE')
a('X4-23','Docs','Runbook fingerprint and Query C checksum checked automatically against the files','Owner never checks against an outdated value','P3','Medium','S','—','Y','N','N','DONE')
a('X4-24','Tests','Data-integrity invariants (invariants.sql) after the busiest stress scenarios','Catches silent corruption under load','P3','Medium','S','—','Y','N','N','DONE')
a('X4-25','Tests','Mutation testing extended: 47 page / 10 SQL mutations','Proves the new tests guard the new rules','P3','Medium','S','—','Y','N','N','DONE')
a('X4-26','Time','Force Central time for viewers in another time zone','Only matters if someone works from elsewhere','P4','Low','M','owner decision','Y','Y','N','DEFERRED')
a('X4-27','Performance','Inventory page with 10,000 products renders slowly (beyond the 1,000-row server limit, so not reachable today)','Future catalogue growth','P4','Low','M','—','Y','N','N','DEFERRED')

# ---------------- Extension 5 (2026-10-06, deep readiness continued)
a('X5-01','Purchasing','Receive used the lines / shipping / tax the page had loaded (another tab\'s changes ignored: removed lines stocked and charged)','Stock and expenses wrong after stale-tab receive (live on main)','P1','High','S','—','Y','N','N','DONE')
a('X5-02','Purchasing','A line change landing while receiving is reported (cause named; final re-check); the editor is warned too','False clean success','P1','High','S','—','Y','N','N','DONE')
a('X5-03','Purchasing','Line guard extended to add and quantity change (5 and 6 of 20 races broke the match even with R1); lock order deadlock-free; forced interleavings','Order vs stock mismatch','P1','High','S','R1; approval','P','Y','Y','BLOCKED-PROD',['X4-15'])
a('X5-04','Orders','Manual order retry adopted a same-number order (numbers are not unique)','A whole order merged into another','P1','High','S','—','Y','N','N','DONE')
a('X5-05','Orders','Orders saved without items listed on sign-in (works across tabs, devices, restarts)','Silently empty orders after a closed tab','P2','Medium','S','—','Y','N','N','DONE')
a('X5-06','Install','A double Run of the install failed with a catalog duplicate-key error; advisory lock added to install / rollback / guard','Alarming error for the owner','P2','Medium','S','—','Y','N','N','DONE')
a('X5-07','Install','Adversarial install tests: concurrent, third install, wrong body, extra index, partial rollback, reads during install, missing auth.uid (61 checks)','Install safety evidence','P3','Medium','S','—','Y','N','N','DONE')
a('X5-08','Customer service','Inquiry reply drafts overwrote each other silently','Lost reply text','P2','Medium','S','—','Y','N','N','DONE')
a('X5-09','Accounting','Money totals paged by position: a record created mid-read was counted twice / another missed','Silent wrong totals','P1','High','S','—','Y','N','N','DONE')
a('X5-10','Audit','Activity "Load more" and export repeated rows when changes arrived meanwhile','Duplicate audit rows in exports','P2','Medium','S','—','Y','N','N','DONE')
a('X5-11','Idempotency','Request keys (unique client_request_id) for record-creating writes (25 paths)','A lost reply plus a retry can still create a duplicate record (mitigated: lock + honest message)','P2','Medium','M','approval (schema change)','N','Y','Y','BLOCKED-PROD')
a('X5-12','Validation','Unreadable number text ($12.50, 12-) reported as "empty"','Confusing message','P3','Low','S','—','Y','N','N','DONE')
a('X5-13','Privacy','Manual-order attempt record kept customer name / e-mail in browser storage','PII on shared devices','P3','Low','S','—','Y','N','N','DONE')
a('X5-14','Tests','Failure matrix 14 actions x 14 kinds (silent refusal, empty reply, offline added); state machines from one fixture; mutation 57 + SQL 11','Evidence breadth','P3','Medium','M','—','Y','N','N','DONE')
a('X5-15','Audit','employee_activity ordering ties: the RPC\'s ORDER BY (needs happened_at, id) is not visible from the dashboard','Possible skip at equal timestamps (owner/Query C check)','P3','Low','S','Query C / owner','N','Y','N','BLOCKED-QC')
a('X5-16','Inventory','Low-stock threshold save was last-write-wins between two tabs; now only over the level shown','Minor overwrite','P3','Low','S','—','Y','N','N','DONE')

# ---------------- Extension 6 (2026-10-07, deep readiness; docs/ops/DEEP_PLATFORM_EXTENSION_6_2026-10-07.md)
a('X6-01','Purchasing','PO line guard did not protect the dashboard\'s step-by-step receive (only R1): a line deleted / re-quantified in the instant between the guard\'s check and its commit was still stocked','Forced every time locally (po_browser_path_races.sh); NOWAIT order lock drafted, 12/12 agree','P1','High','S','approval','N','Y','Y','BLOCKED-PROD',['X5-03','X4-15'])
a('X6-02','Accounting','A total that is really zero showed "-$0.00" (0.30 - (0.10+0.20) in floating point); live on main','fmtMoney rounds to cents, no minus on zero','P2','Medium','S','—','Y','N','N','DONE')
a('X6-03','Accounting','Count-up animation re-formatted figures in the browser language ("$25.000,00" on a German computer); live on main','Last frame shows the exact target in US format','P3','Low','S','—','Y','N','N','DONE')
a('X6-04','Orders','Notice "re-enter the same order on this device" made a SECOND order once the tab was closed (attempt lives in the tab only)','"Finish this order" adds the items to that order or refuses','P2','High','S','—','Y','N','N','DONE')
a('X6-05','Privacy','Sign-out only hid the dashboard: customer names, e-mails, figures stayed in the page / memory for the next person on a shared computer; live on main','Sign-out reloads the page','P1','High','S','—','Y','N','N','DONE')
a('X6-06','Privacy','Manual-order sign-out left the typed customer name / e-mail in the hidden form','Sign-out reloads; deliberate sign-out forgets the attempt','P2','Medium','S','—','Y','N','N','DONE')
a('X6-07','Emergency','A lost reply on the Order Sync / Agent #7 safety step was reported as "could NOT", although it may have happened','Says "may or may not", check by hand','P3','Medium','S','—','Y','N','N','DONE')
a('X6-08','Errors','Deadlock / statement timeout / busy row shown as raw database text','Plain words: the step was undone, nothing changed by it','P3','Low','S','—','Y','N','N','DONE')
a('X6-09','Tests','Hidden conditional skip: the "5..5" number-box case never ran (Chromium turns it into 5.5)','Premise asserted; "box shows X, X is saved" tested','P2','Medium','S','—','Y','N','N','DONE')
a('X6-10','Tests','No tool accounted for skipped tests: a test could silently stop running','tests/tools/skip-report.js; every skip classified','P2','Medium','S','—','Y','N','N','DONE')
a('X6-11','Accounting','Daily Summary and home "Today\'s revenue" counted Canceled / CANCELLED / refunded orders (rule: only the exact word "cancelled"); live on main','Same classifyOrderStatus rule as Accounting','P1','High','S','—','Y','N','N','DONE')
a('X6-12','Accounting','Orders page "Total revenue" = newest 300 orders only, cancelled included, labelled as the total; live on main','Accounting rule + honest label when capped','P2','High','S','—','Y','N','N','DONE')
a('X6-13','Accounting','Totals labelled with the first order\'s currency and summed across currencies without warning','Plain warning on Accounting, Tax Records, Daily Summary, Orders','P3','Medium','S','—','Y','N','N','DONE')
a('X6-14','Orders','Orders saved without items still count as revenue in Accounting','Now listed on Accounting ("Orders saved without items"), on the manual-order page for the person who entered them, and in Query E; whether to exclude them from revenue is an accounting decision','P2','Medium','S','owner / accountant','P','Y','N','BLOCKED-OWNER')
a('X6-15','Idempotency','Request keys drafted (drafts/19 + rollback 20) for the 22 create tables; local test 23/23','Retried creates cannot duplicate once installed and the dashboard sends keys','P2','High','M','approval; then dashboard PR','N','Y','Y','BLOCKED-PROD',['X5-11'])
a('X6-16','Inventory','Read-only stock reconciliation (Query E) prepared with owner guide; local test 24/24','Staff / owner can see stock vs history, deliveries vs stock and expense','P2','High','S','owner runs','N','Y','N','BLOCKED-OWNER')
a('X6-17','Security','This session\'s GitHub credential has ADMIN rights on the repository (CLAUDE.md expects the non-admin stasvitiuk-reos); the protect-main ruleset lets admins bypass. Not used','Least privilege for automated sessions','P1','High','S','owner: connect Claude with a non-admin account','N','Y','N','BLOCKED-OWNER')
a('X6-18','SQL','drafts/13 (report totals) was three statements without a transaction','Now all-or-nothing','P3','Low','S','—','Y','N','N','DONE')
a('X6-19','SQL','No automatic safety check over the SQL drafts (search_path, definer, grants, RLS, dynamic SQL, rollback named)','sql-drafts-static.spec.js (26 checks)','P2','Medium','S','—','Y','N','N','DONE')
a('X6-20','Tests','Local SQL scripts shared test users; one left a role behind and made the stress test fail 79 checks','Own users per script; stress resets roles','P3','Medium','S','—','Y','N','N','DONE')
a('X6-21','Concurrency','2 / 5 / 10 operators on one task / return at once','Exactly one change; others told; no false success','P3','Medium','S','—','Y','N','N','DONE')
a('X6-22','Browser','Signed file links open with window.open after an await: Safari (especially iPhone) may block the new tab silently','Needs a real-device check; same on main','P3','Medium','S','real iPhone check','N','Y','N','BLOCKED-OWNER',['RS-03'])
a('X6-23','Validation','Chromium drops characters while typing in number boxes ("1.2.3" -> 1.23, "1,200" -> 1200); the box shows the result','Browser behaviour; "shown = saved" is tested','P4','Low','S','—','N','N','N','DEFERRED')
a('X6-24','Accounting','Range "This month" has no upper bound: a future-dated (imported / clock-skewed) order counts now','Data error case; documented','P4','Low','S','—','Y','N','N','DEFERRED')
a('X6-26','Inventory','Design note: a future function that inserts PO lines AND calls R1 in one transaction must lock the order (FOR UPDATE) before inserting, or two concurrent copies deadlock (foreign-key share lock then R1 row lock). Not reachable from the dashboard (separate requests); found as a stress-test artifact (S29) and fixed in the test','Avoid a future lock-upgrade deadlock','P4','Low','S','—','Y','N','N','DEFERRED')
a('X6-25','Purchasing','PO cases A-J reviewed; permission removed mid-receive test added','Coverage map in PO_RECEIVE_RACE_REVIEW section 0','P2','Medium','S','—','Y','N','N','DONE')

# Extension 7 (2026-10-07)
a('X7-01','Reports','Tax Records "by state" split one state into several rows ("CA", "California", " california ")','One row per state; independent oracle test','P1','High','S','—','Y','N','N','DONE')
a('X7-02','Reports','Tax Records cost estimate matched SKUs case-sensitively ("syn-a" missed "SYN-A")','Estimate exact; oracle test','P1','High','S','—','Y','N','N','DONE')
a('X7-03','Reports','A money figure could freeze part-way through its count-up animation under load','Timer fallback; test fails without it','P2','Medium','S','—','Y','N','N','DONE')
a('X7-04','Workflows','Tasks, Approvals and Incidents read the first 100 rows of every status, so enough closed rows hid open ones','Open-only reads; 4 tests fail on the old code','P1','High','S','—','Y','N','N','DONE')
a('X7-05','Owner UX','No way to see recently finished tasks or reopen one','Recently finished + guarded Reopen (done -> open only)','P2','Medium','S','—','Y','N','N','DONE')
a('X7-06','Owner UX','One failed Business Health read blanked the whole panel','Per-tile "?" with a plain reason; work tiles open their page','P2','Medium','S','—','Y','N','N','DONE')
a('X7-07','Owner UX','Typed-but-unsaved work was lost silently on close / reload / sign out','Question first; forced sign-out never waits','P2','Medium','S','—','Y','N','N','DONE')
a('X7-08','Truthfulness','Business Continuity showed an unknown or missing status as "Operational" and left it out of the counts','Shown and counted as Unknown; guarded on the real value','P2','Medium','S','—','Y','N','N','DONE')
a('X7-09','Concurrency','SOP agent switch guessed its state after a stale refusal','Re-reads','P3','Low','S','—','Y','N','N','DONE')
a('X7-10','Idempotency','Adding a supplier after a lost reply could duplicate it','Same-name question (case-insensitive, literal); full fix = request keys (X6-15)','P3','Medium','S','—','Y','N','N','DONE',['X6-15'])
a('X7-11','Security','A different person signing in elsewhere left the previous person\'s data in the open tab (dashboard and order page)','Tab wipes on user change; same-person refresh ignored','P1','High','S','—','Y','N','N','DONE')
a('X7-12','Idempotency','No machine-readable list of write paths with a retry class','MUTATION_WRITE_PATH_INVENTORY.json: 70 safe, 6 client-side, 23 request key, 0 unresolved; kept current by a test','P3','Medium','S','—','Y','N','N','DONE')
a('X7-13','Concurrency','R1-R5 had fixed-order stress only','random_interleavings.sh: no guard 75/300 failing, both guards 0/300, minimal repro found','P2','Medium','S','—','Y','N','N','DONE')
a('X7-14','Permissions','Employees can approve requests in the database; admin switches have no page-side role check; policies of tables outside the export unknown','ROLE_PERMISSION_MATRIX.md §4; Query D answers','P2','High','S','owner decision + Query D','N','Y','Y','BLOCKED-OWNER')
a('X7-15','Owner UX','Wide tables scroll sideways at 390 / 320 px (last column cut until scrolled)','Pre-existing; card layout for phones later','P3','Low','M','—','Y','N','N','OPEN')
a('X7-16','Recovery','Restore drill into a throwaway Supabase project never recorded','Only proof that backups work','P1','High','S','owner backup check first','N','Y','Y','BLOCKED-OWNER')
# ---------------- Extension 8 (2026-10-07 .. 10-10)
a('X8-01','Owner UX','Waiting customer questions could be hidden behind answered ones','All waiting read; answered capped at 100 with exact count','P1','High','S','—','Y','N','N','DONE')
a('X8-02','Returns','Returns only possible for the newest 200 orders','Older-order finder','P1','High','S','—','Y','N','N','DONE')
a('X8-03','Search','Sidebar search silently missed older orders','Look up in all orders (literal match)','P2','Medium','S','—','Y','N','N','DONE')
a('X8-04','Owner UX','Recycle bins / histories stopped at 50 with no hint','Showing N of M + Show more on 6 lists','P2','Medium','S','—','Y','N','N','DONE')
a('X8-05','Compliance','Evidence picker missed older open incidents','Open incidents of any age + newest 200','P2','Medium','S','—','Y','N','N','DONE')
a('X8-06','Navigation','Browser Back left the dashboard','Page history, Back/Forward, deep links','P2','Medium','S','—','Y','N','N','DONE')
a('X8-07','Security','Back-button cache could show the page after sign-out','Session re-checked on back-cache return','P1','High','S','—','Y','N','N','DONE')
a('X8-08','Reporting','This Week meant different windows on Orders and Expenses','One Last 7 days window; Central-clock oracle','P2','Medium','S','—','Y','N','N','DONE',['F3-07'])
a('X8-09','Concurrency','Product edit lost update across tabs','Conditional on updated_at','P1','High','S','—','Y','N','N','DONE')
a('X8-10','Concurrency','PO shipping/tax lost update across tabs','Conditional on values shown','P1','High','S','—','Y','N','N','DONE')
a('X8-11','Reporting','Slower older replies drew over newer ones (5 pages)','Latest request wins','P1','High','S','—','Y','N','N','DONE')
a('X8-12','Security','No Content-Security-Policy on 5 pages','Strict policy on every page','P2','Medium','S','—','Y','N','N','DONE',['S7'])
a('X8-13','Owner UX','No single list of what needs a look','Home Checks card: 17 deterministic checks, UNKNOWN distinct from fine','P1','High','M','—','Y','N','N','DONE')
a('X8-14','Integrity','No daily integrity check','Query F (read-only, 15 checks, 33/33 local)','P1','High','S','—','Y','N','N','DONE')
a('X8-15','Integrity','Run Query F once, then schedule it nightly','Baseline + ongoing detection','P1','High','S','owner runs; pg_cron approval','N','Y','Y','BLOCKED-OWNER')
a('X8-16','Recovery','Restore procedure never rehearsed','Local restore drill 6/6 (production drill = X7-16)','P2','Medium','S','—','Y','N','N','DONE')
a('X8-17','Review','No safe staging review copy','Synthetic-data build + test; publishing needs owner choice','P2','Medium','M','owner choice of host (X8-D1)','Y','Y','N','BLOCKED-OWNER')
a('X8-18','Recovery','Backup status visible on Home','Backup job writes one read-only status row (D5)','P2','Medium','M','owner approval; private repo change','N','Y','Y','BLOCKED-OWNER')
a('X8-19','Owner UX','One shared warning banner: a background Accounting load can replace the Tax Records currency warning with the same warning labelled Accounting','Show each page currency warning only while that page is open (found by the EXT8 x3 run; test made race-free)','P3','Low','S','—','Y','N','N','OPEN')

if __name__ == '__main__':
    import collections, os
    order = {'P0':0,'P1':1,'P2':2,'P3':3,'P4':4}
    st = collections.Counter(i['status'] for i in I)
    pr = collections.Counter((i['p'], i['status']=='DONE') for i in I)
    merged = sum(len(i['merged']) for i in I)
    out = []
    out.append('# Master platform backlog (2026-10-06)\n')
    out.append('Internal dashboard/platform only. Generated from `docs/ops/backlog/items.py` (edit the data there, then run `python3 docs/ops/backlog/items.py`). No production secrets or private business data.\n')
    out.append(f'**{len(I)} deduplicated items** from {len(I)+merged} raw candidates ({merged} duplicates merged: the same item recorded in PROJECT_RECORD, the overnight review, PRs, owner lists, decision registers and tests).\n')
    out.append('Status counts: ' + ', '.join(f'{k} {v}' for k,v in sorted(st.items())) + '\n')
    rows = []
    for p in ['P0','P1','P2','P3','P4']:
        tot = sum(1 for i in I if i['p']==p); done = sum(1 for i in I if i['p']==p and i['status']=='DONE')
        rows.append(f'| {p} | {tot} | {done} | {tot-done} |')
    out.append('| Priority | Items | Done (branch) | Remaining |\n|---|---|---|---|\n' + '\n'.join(rows) + '\n')
    out.append('Priorities: P0 data loss / security / financial corruption / destructive · P1 launch blocker / correctness / concurrency / permission · P2 reliability / scale / accessibility / major UX · P3 maintainability / tests / docs · P4 future.\n')
    out.append('"Done" = implemented and tested on the branch chain ending at `claude/platform-deep-readiness-extension-7` — **not merged, not live**.\n')
    for p in ['P0','P1','P2','P3','P4']:
        out.append(f'\n## {p}\n')
        out.append('| ID | Area | Item | Why it matters | Launch impact | Effort | Depends on | Safe in branch | Owner | Prod | Status |')
        out.append('|---|---|---|---|---|---|---|---|---|---|---|')
        for i in sorted([x for x in I if x['p']==p], key=lambda x:(x['status']=='DONE', x['id'])):
            out.append(f"| {i['id']} | {i['area']} | {i['title']} | {i['why']} | {i['impact']} | {i['effort']} | {i['deps']} | {i['safe']} | {i['owner']} | {i['prod']} | {i['status']} |")
    out.append('\n## Merged duplicates (provenance)\n')
    for i in I:
        if i['merged']: out.append(f"- {i['id']}: {', '.join(i['merged'])}")
    path = os.path.join(os.path.dirname(__file__), '..', 'MASTER_PLATFORM_BACKLOG_2026-10-06.md')
    open(path,'w').write('\n'.join(out) + '\n')
    print(len(I), 'items;', merged, 'merged;', dict(st))
