// Builds the STAGING review copy of the dashboard (EXT8, workstream O).
//
//   node tests/tools/staging/build-staging.js <out-dir>
//
// The copy runs entirely in the browser on SYNTHETIC data:
//   * every database / sign-in call is answered inside the page by the same
//     fake Supabase the tests use (tests/helpers/mock-supabase.js), bundled
//     into staging-runtime.js, with the data from staging-seed.js
//   * the production database address and key are REPLACED by a placeholder
//     host that does not exist (staging-demo.invalid), and the page's
//     Content-Security-Policy only allows that host, so even a bug in the
//     stand-in cannot reach production
//   * any other outside address is refused by the stand-in
//   * a permanent "DEVELOPMENT / STAGING — NOT PRODUCTION" banner, and a
//     button that signs in as the synthetic owner (nobody types a password)
//   * nothing is saved anywhere: a reload starts again from the seed
// The build refuses to finish if any trace of the production address or key
// is left in the output.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', '..');
const OUT = path.resolve(process.argv[2] || path.join(ROOT, 'staging-build'));
const PROD_HOST = 'uizrazyehilyzmwttsrn.supabase.co';
const PROD_KEY = 'sb_publishable_n0sEzZK0JMtwgk280a3YXA_zxtnheqj';
const DEMO_HOST = 'staging-demo.invalid';

function read(rel) { return fs.readFileSync(path.join(ROOT, rel), 'utf8'); }
// The production address / key are replaced everywhere (page AND bundled test
// helpers, which name the production host as the address they intercept).
function scrub(text) { return text.split(PROD_HOST).join(DEMO_HOST).split(PROD_KEY).join('staging-demo-key-not-real'); }

// ---- 1. the in-page stand-in for Supabase ---------------------------------
const MODULES = {
  './db-constraints': 'tests/helpers/db-constraints.js',
  '../fixtures/synthetic-data': 'tests/fixtures/synthetic-data.js',
  'mock-supabase': 'tests/helpers/mock-supabase.js',
  'staging-seed': 'tests/tools/staging/staging-seed.js',
};
let bundle = `/* STAGING ONLY. Generated by tests/tools/staging/build-staging.js. Synthetic data; never contacts production. */
(function () {
  'use strict';
  var Buffer = { from: function (s) { return { toString: function () { return btoa(unescape(encodeURIComponent(String(s)))); } }; } };
  var nodeStubs = {
    fs: { readFileSync: function () { throw new Error('no files in staging'); }, existsSync: function () { return false; }, statSync: function () { return { isDirectory: function () { return true; } }; } },
    path: { resolve: function () { return Array.prototype.join.call(arguments, '/'); }, join: function () { return Array.prototype.join.call(arguments, '/'); }, extname: function (p) { var m = /\\.[^./]*$/.exec(p); return m ? m[0] : ''; }, sep: '/' },
  };
  var defs = {}, cache = {};
  function req(name) {
    if (nodeStubs[name]) return nodeStubs[name];
    if (cache[name]) return cache[name].exports;
    var m = cache[name] = { exports: {} };
    defs[name](m, m.exports, req, '/');
    return m.exports;
  }
`;
for (const [name, file] of Object.entries(MODULES)) {
  bundle += `  defs[${JSON.stringify(name)}] = function (module, exports, require, __dirname) {\n${scrub(read(file))}\n};\n`;
}
bundle += `
  var FakeSupabase = req('mock-supabase').FakeSupabase;
  var backend = new FakeSupabase();
  var seed = req('staging-seed').stagingTables(Date.now());
  Object.keys(seed).forEach(function (t) { backend.tables[t] = seed[t]; });
  backend.allowUnguardedState = true; backend.expectViolations = true; backend.allowImpossibleData = true;
  backend.rpc.list_my_sessions = [{ session_id: 'staging-session', created_at: new Date().toISOString(), updated_at: new Date().toISOString(), user_agent: 'Staging browser', ip: '0.0.0.0', is_current: true }];
  window.__STAGING_OWNER = req('../fixtures/synthetic-data').OWNER_USER;
  var realFetch = window.fetch.bind(window);
  window.fetch = function (input, init) {
    var isReq = typeof Request !== 'undefined' && input instanceof Request;
    var url = new URL(isReq ? input.url : String(input), location.href);
    if (url.hostname !== ${JSON.stringify(DEMO_HOST)}) {
      if (url.origin === location.origin) return realFetch(input, init);
      return Promise.reject(new TypeError('Staging: outside address refused: ' + url.host));
    }
    var method = String((init && init.method) || (isReq && input.method) || 'GET').toUpperCase();
    var headers = {};
    new Headers((init && init.headers) || (isReq ? input.headers : {})).forEach(function (v, k) { headers[k] = v; });
    var bodyP = init && init.body != null ? Promise.resolve(String(init.body)) : (isReq && method !== 'GET' && method !== 'HEAD' ? input.clone().text() : Promise.resolve(null));
    return bodyP.then(function (body) {
      return new Promise(function (resolve) {
        var route = {
          request: function () { return { url: function () { return url.href; }, method: function () { return method; }, postData: function () { return body || null; }, headers: function () { return headers; } }; },
          fulfill: function (r) {
            var h = Object.assign({}, r.headers || {});
            if (r.contentType) h['content-type'] = r.contentType;
            var noBody = r.status === 204 || r.status === 304;
            resolve(new Response(noBody ? null : (r.body == null ? '' : r.body), { status: r.status || 200, headers: h }));
          },
          abort: function () { resolve(Response.error()); },
          fallback: function () { resolve(new Response('[]', { status: 200, headers: { 'content-type': 'application/json' } })); },
        };
        Promise.resolve(backend.handle(route)).catch(function (e) {
          resolve(new Response(JSON.stringify({ message: 'staging stand-in error: ' + e }), { status: 500, headers: { 'content-type': 'application/json' } }));
        });
      });
    });
  };
  if (typeof WebSocket !== 'undefined') window.WebSocket = function () { throw new Error('Staging: live connections are off'); };

  function banner() {
    if (document.getElementById('stagingBanner')) return;
    var b = document.createElement('div');
    b.id = 'stagingBanner';
    b.setAttribute('role', 'note');
    b.textContent = 'DEVELOPMENT / STAGING — NOT PRODUCTION · synthetic data only · nothing is saved: reloading starts over · not connected to the real database, Shopify or e-mail';
    b.style.cssText = 'position:sticky;top:0;z-index:100000;background:#7a2e0e;color:#fff;font:600 13px/1.4 -apple-system,system-ui,sans-serif;padding:8px 14px;text-align:center;letter-spacing:.02em';
    document.body.insertBefore(b, document.body.firstChild);
    var form = document.getElementById('loginForm');
    if (form && !document.getElementById('stagingSignIn')) {
      var box = document.createElement('div');
      box.style.cssText = 'margin:12px 0;padding:10px 12px;border-radius:10px;background:#fff4dd;color:#5c3b00;font-size:13px';
      box.innerHTML = '<b>Staging review copy.</b> Do not type a real password here. Use the button: it signs in as the synthetic owner.<br>';
      var btn = document.createElement('button');
      btn.type = 'button'; btn.id = 'stagingSignIn'; btn.textContent = 'Sign in as the synthetic owner';
      btn.style.marginTop = '8px';
      btn.addEventListener('click', function () {
        document.getElementById('email').value = window.__STAGING_OWNER.email;
        document.getElementById('password').value = window.__STAGING_OWNER.password;
        document.getElementById('loginBtn').click();
      });
      box.appendChild(btn);
      form.parentNode.insertBefore(box, form);
    }
  }
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', banner); else banner();
})();
`;

// ---- 2. the page ----------------------------------------------------------
let html = read('owner-login.html');
const before = html.length;
html = scrub(html);
html = html.replace(/<title>([^<]*)<\/title>/, '<title>STAGING — $1</title>');
// The stand-in must be installed before the Supabase library and the page.
html = html.replace(/(<script src="https:\/\/cdn\.jsdelivr\.net\/npm\/@supabase)/, '<script src="staging-runtime.js"></script>\n$1');
if (!html.includes('staging-runtime.js')) throw new Error('could not insert the staging runtime');
for (const bad of [PROD_HOST, PROD_KEY, 'uizrazyehilyzmwttsrn']) {
  if (html.includes(bad) || bundle.includes(bad)) throw new Error('production trace left in the staging build: ' + bad);
}

fs.mkdirSync(path.join(OUT, 'assets'), { recursive: true });
fs.writeFileSync(path.join(OUT, 'index.html'), html);
fs.writeFileSync(path.join(OUT, 'staging-runtime.js'), bundle);
for (const a of fs.readdirSync(path.join(ROOT, 'assets'))) fs.copyFileSync(path.join(ROOT, 'assets', a), path.join(OUT, 'assets', a));
console.log('staging build written to', OUT, '(page', before, '->', html.length, 'bytes; runtime', bundle.length, 'bytes)');
